# Change these first
owner: jessicaroh # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Habaneros
    url: https://habaneros.ch
    maxResponseTime: 120000
  - name: Garage Union
    url: https://garageunion.ch
    maxResponseTime: 120000
  - name: Boucherie La Lienne
    url: https://boucherielalienne.ch
    maxResponseTime: 120000
  - name: Pascal Héritier
    url: https://pascal-heritier.ch
    maxResponseTime: 120000
  - name: RR Jantes
    url: https://rrjantes.ch
    maxResponseTime: 120000
  - name: AF Conseils
    url: https://afconseils.ch
    maxResponseTime: 120000
  - name: S1
    url: https://s1.stevenroh.ch
    __dangerous__insecure: true
    maxResponseTime: 120000
    expectedStatusCodes:
      - 404
  - name: S2
    url: https://s2.stevenroh.ch
    maxResponseTime: 120000
    expectedStatusCodes:
      - 404
  - name: S3
    url: https://s3.stevenroh.ch
    __dangerous__insecure: true
    maxResponseTime: 120000
    expectedStatusCodes:
      - 404
  - name: H
    url: https://h.stevenroh.ch
    maxResponseTime: 120000
    expectedStatusCodes:
      - 404
    

status-website:
  logoUrl: https://habaneros.ch/wp-content/uploads/2023/03/logo_habaneros.svg
  baseUrl: /uptime # where "repo" is your repository name
  faviconSvg: https://habaneros.ch/wp-content/uploads/2023/03/logo_habaneros.svg
  name: Habaneros uptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
